### ISSUE TITLE
Error running the kinesis_lambda_function.py

### ISSUE THREAD

**Issue by chaqattack** [pauld-splunk/aws-splunk-firehose-error-reingest#5]
I am getting this error processing cloudwatch logs to splunk 

[ERROR] UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byteTraceback (most recent call last):  File "/var/task/kinesis_lambda_function.py", line 127, in handler    records = list(processRecords(event['records']))  File "/var/task/kinesis_lambda_function.py", line 17, in processRecords    data = json.loads(base64.b64decode(r['data']))  File "/var/lang/lib/python3.8/json/__init__.py", line 343, in loads    s = s.decode(detect_encoding(s), 'surrogatepass') | [ERROR] UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte Traceback (most recent call last):   File "/var/task/kinesis_lambda_function.py", line 127, in handler     records = list(processRecords(event['records']))   File "/var/task/kinesis_lambda_function.py", line 17, in processRecords     data = json.loads(base64.b64decode(r['data']))   File "/var/lang/lib/python3.8/json/__init__.py", line 343, in loads     s = s.decode(detect_encoding(s), 'surrogatepass')
-- | --

**Comment by animetauren** [comment]
@chaqattack python is complaining that you passed a gzip file instead of a json file that it was expecting. 

To verify this is the case check what is the "event" you are passing to the Lambda function. A simple way to do this is to add a `print(event)` at the top of the handler function.
